<Project>
  <PropertyGroup>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <TreatWarningsAsErrors Condition="'$(MSBuildProjectName)' != 'Guardian.Tests'">true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
